server:
  port: 7979
spring:
  application:
    name: ddsh-base-hystrix-server
management:
  endpoint:
    shutdown:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/